### ISSUE TITLE
SEO underlag

### ISSUE THREAD

**Issue by marypope19** [chas-team-5/u03-quiz-app#43]
Dokument för SEO på vår quiz app
https://docs.google.com/document/d/1_N80w5Bp-CwJbMmvIWX1nRCGlMbhDapmFF8c7U6Opp0/edit?usp=sharing

**Comment by cribepencheff** [comment]
Kolla gärna igenom så att vi kan sätta denna issue som done.
@Benckert @Saif-SS @cribepencheff @marypope19
